// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package profiling

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadProcessMonitor returns the embedded CollectionSpec for processMonitor.
func loadProcessMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load processMonitor: %w", err)
	}

	return spec, err
}

// loadProcessMonitorObjects loads processMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*processMonitorObjects
//	*processMonitorPrograms
//	*processMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcessMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcessMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// processMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processMonitorSpecs struct {
	processMonitorProgramSpecs
	processMonitorMapSpecs
	processMonitorVariableSpecs
}

// processMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processMonitorProgramSpecs struct {
	SyncfuzzProcessExec *ebpf.ProgramSpec `ebpf:"syncfuzz_process_exec"`
	SyncfuzzProcessExit *ebpf.ProgramSpec `ebpf:"syncfuzz_process_exit"`
	SyncfuzzProcessFork *ebpf.ProgramSpec `ebpf:"syncfuzz_process_fork"`
}

// processMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processMonitorMapSpecs struct {
	Events       *ebpf.MapSpec `ebpf:"events"`
	TargetCgroup *ebpf.MapSpec `ebpf:"target_cgroup"`
}

// processMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processMonitorVariableSpecs struct {
}

// processMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcessMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type processMonitorObjects struct {
	processMonitorPrograms
	processMonitorMaps
	processMonitorVariables
}

func (o *processMonitorObjects) Close() error {
	return _ProcessMonitorClose(
		&o.processMonitorPrograms,
		&o.processMonitorMaps,
	)
}

// processMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcessMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type processMonitorMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	TargetCgroup *ebpf.Map `ebpf:"target_cgroup"`
}

func (m *processMonitorMaps) Close() error {
	return _ProcessMonitorClose(
		m.Events,
		m.TargetCgroup,
	)
}

// processMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcessMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type processMonitorVariables struct {
}

// processMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcessMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type processMonitorPrograms struct {
	SyncfuzzProcessExec *ebpf.Program `ebpf:"syncfuzz_process_exec"`
	SyncfuzzProcessExit *ebpf.Program `ebpf:"syncfuzz_process_exit"`
	SyncfuzzProcessFork *ebpf.Program `ebpf:"syncfuzz_process_fork"`
}

func (p *processMonitorPrograms) Close() error {
	return _ProcessMonitorClose(
		p.SyncfuzzProcessExec,
		p.SyncfuzzProcessExit,
		p.SyncfuzzProcessFork,
	)
}

func _ProcessMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed processmonitor_bpfeb.o
var _ProcessMonitorBytes []byte
