// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64) && linux

package profiling

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type resourceMonitorPendingResourceSyscall struct {
	CgroupId uint64
	Arg0     uint64
	Kind     uint32
	Path     [128]int8
	_        [4]byte
}

// loadResourceMonitor returns the embedded CollectionSpec for resourceMonitor.
func loadResourceMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ResourceMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load resourceMonitor: %w", err)
	}

	return spec, err
}

// loadResourceMonitorObjects loads resourceMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*resourceMonitorObjects
//	*resourceMonitorPrograms
//	*resourceMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadResourceMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadResourceMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// resourceMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type resourceMonitorSpecs struct {
	resourceMonitorProgramSpecs
	resourceMonitorMapSpecs
	resourceMonitorVariableSpecs
}

// resourceMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type resourceMonitorProgramSpecs struct {
	SyncfuzzResourceEnter *ebpf.ProgramSpec `ebpf:"syncfuzz_resource_enter"`
	SyncfuzzResourceExit  *ebpf.ProgramSpec `ebpf:"syncfuzz_resource_exit"`
}

// resourceMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type resourceMonitorMapSpecs struct {
	Events          *ebpf.MapSpec `ebpf:"events"`
	PendingSyscalls *ebpf.MapSpec `ebpf:"pending_syscalls"`
	TargetCgroup    *ebpf.MapSpec `ebpf:"target_cgroup"`
}

// resourceMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type resourceMonitorVariableSpecs struct {
}

// resourceMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadResourceMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type resourceMonitorObjects struct {
	resourceMonitorPrograms
	resourceMonitorMaps
	resourceMonitorVariables
}

func (o *resourceMonitorObjects) Close() error {
	return _ResourceMonitorClose(
		&o.resourceMonitorPrograms,
		&o.resourceMonitorMaps,
	)
}

// resourceMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadResourceMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type resourceMonitorMaps struct {
	Events          *ebpf.Map `ebpf:"events"`
	PendingSyscalls *ebpf.Map `ebpf:"pending_syscalls"`
	TargetCgroup    *ebpf.Map `ebpf:"target_cgroup"`
}

func (m *resourceMonitorMaps) Close() error {
	return _ResourceMonitorClose(
		m.Events,
		m.PendingSyscalls,
		m.TargetCgroup,
	)
}

// resourceMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadResourceMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type resourceMonitorVariables struct {
}

// resourceMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadResourceMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type resourceMonitorPrograms struct {
	SyncfuzzResourceEnter *ebpf.Program `ebpf:"syncfuzz_resource_enter"`
	SyncfuzzResourceExit  *ebpf.Program `ebpf:"syncfuzz_resource_exit"`
}

func (p *resourceMonitorPrograms) Close() error {
	return _ResourceMonitorClose(
		p.SyncfuzzResourceEnter,
		p.SyncfuzzResourceExit,
	)
}

func _ResourceMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed resourcemonitor_bpfel.o
var _ResourceMonitorBytes []byte
